// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import EditorController from "./editor_controller";
application.register("editor", EditorController);

import SearchController from "./search_controller";
application.register("search", SearchController);

import UploadController from "./upload_controller";
application.register("upload", UploadController);
