height: 500
menubar: false
toolbar:
  - undo redo anchor link table code image | formatselect | bold italic backcolor codesample | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help
plugins:
  - advlist autolink lists link image charmap preview anchor
  - searchreplace visualblocks code fullscreen codesample
  - insertdatetime media table code help wordcount image